apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atapp-staging

resources:
  - ../../base

images:
  - name: atapp-server
    newName: atapp-server
    newTag: staging

replicas:
  - name: atapp-server
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: atapp-server-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: atapp-server-config
      data:
        APP_ENV: staging
        ALLOWED_ORIGINS: "https://staging.app.example.com"
